"""business workflows, registry, governance

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-10 05:54:28.623780
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('connector', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('departments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_connections_connector'), 'connections', ['connector'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designer_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=40), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('undo_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('redo_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designer_sessions_user_id'), 'designer_sessions', ['user_id'], unique=False)
    op.create_table('schedule_fires',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'slot')
    )
    op.create_table('inbox_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_items_user_id'), 'inbox_items', ['user_id'], unique=False)
    op.add_column('agents', sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('approvals', sa.Column('department', sa.String(length=40), nullable=True))
    op.add_column('approvals', sa.Column('required_role', sa.String(length=20), server_default='approver', nullable=False))
    op.add_column('approvals', sa.Column('separation_of_duties', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('memberships', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('workflow_runs', sa.Column('mode', sa.String(length=20), server_default='real', nullable=False))
    op.add_column('workflow_runs', sa.Column('triggered_by', sa.String(length=20), server_default='manual', nullable=False))
    op.add_column('workflow_runs', sa.Column('department', sa.String(length=40), nullable=True))
    op.add_column('workflow_versions', sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_versions', sa.Column('change_summary', sa.Text(), nullable=True))
    op.add_column('workflows', sa.Column('department', sa.String(length=40), nullable=True))
    op.add_column('workflows', sa.Column('status', sa.String(length=20), server_default='enabled', nullable=False))
    op.add_column('workflows', sa.Column('enabled_version', sa.Integer(), nullable=True))
    op.add_column('workflows', sa.Column('enabled_by', sa.UUID(), nullable=True))
    op.add_column('workflows', sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflows', sa.Column('schedule_cron', sa.String(length=100), nullable=True))
    op.add_column('workflows', sa.Column('schedule_timezone', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_workflows_department'), 'workflows', ['department'], unique=False)
    op.create_foreign_key(None, 'workflows', 'users', ['enabled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_index(op.f('ix_workflows_department'), table_name='workflows')
    op.drop_column('workflows', 'schedule_timezone')
    op.drop_column('workflows', 'schedule_cron')
    op.drop_column('workflows', 'enabled_at')
    op.drop_column('workflows', 'enabled_by')
    op.drop_column('workflows', 'enabled_version')
    op.drop_column('workflows', 'status')
    op.drop_column('workflows', 'department')
    op.drop_column('workflow_versions', 'change_summary')
    op.drop_column('workflow_versions', 'plan')
    op.drop_column('workflow_runs', 'department')
    op.drop_column('workflow_runs', 'triggered_by')
    op.drop_column('workflow_runs', 'mode')
    op.drop_column('users', 'memberships')
    op.drop_column('approvals', 'separation_of_duties')
    op.drop_column('approvals', 'required_role')
    op.drop_column('approvals', 'department')
    op.drop_column('agents', 'profile')
    op.drop_index(op.f('ix_inbox_items_user_id'), table_name='inbox_items')
    op.drop_table('inbox_items')
    op.drop_table('schedule_fires')
    op.drop_index(op.f('ix_designer_sessions_user_id'), table_name='designer_sessions')
    op.drop_table('designer_sessions')
    op.drop_table('files')
    op.drop_index(op.f('ix_connections_connector'), table_name='connections')
    op.drop_table('connections')
    op.drop_table('departments')
    # ### end Alembic commands ###
